packages:
  - .
  - plugins/*

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@lethevimlet/sshift"
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
trustPolicyExclude:
  - "@lethevimlet/sshift"
  - "semver@6.3.1"
ignoreScripts: true